### PR TITLE
Fix for libraries linking

### PR DESCRIPTION
**Pull request by denizzzka**

### CODE REVIEW

**Comment by moon-chilled** [comment]
This doesn't work for me.  I get `/usr/bin/ld: cannot find -lBearLibTerminal`

**Comment by denizzzka** [comment]
What OS and compiler?

**Comment by moon-chilled** [comment]
Linux and I tried ldc and dmd.  I just edited the dub.json to match your changes.

**Comment by denizzzka** [comment]
Reproduced. I am found another library copy in /usr/local in my system.

PR #2 is crap.

**Pull request closed without merging**
